apiVersion: apps/v1
kind: Deployment
metadata:
  name: studybuddy-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: studybuddy-app
  template:
    metadata:
      labels:
        app: studybuddy-app
    spec:
      containers:
      - name: studybuddy-app
        image: atsigman/study_buddy:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
        env:
        - name: GROQ_API_KEY
          valueFrom:
            secretKeyRef:
              name: groq-api-secret
              key: GROQ_API_KEY