apiVersion: v1
kind: Service
metadata:
  name: studybuddy-service
spec:
  selector:
    app: studybuddy-app
  ports:
    - port: 80
      targetPort: 8501  # default port for Streamlit
  type: NodePort